#!/bin/sh
echo "This install script installs i3 WM and related tools. It uses the Xorg protocol."
echo "Dependencies: git, pacman, a vanilla install of Arch Linux with the base-devel package" 

echo "

	" && sleep 5
echo "Packages which will be installed: xorg-xserver, i3-gaps, i3blocks, paru-bin, maim, pulseaudio,
                                  pulseaudio-alsa, pulseaudio-bluetooth, bluez, bluez-utils,
                                  fish (will be set to be default shell), ttf-jetbrains-mono,
                                  pango, nm-applet,  dmenu, ranger, mate-calc, firefox, 
                                  clipmenu, dunst, redshift, feh, light, motivate, alacritty \n
				  \n "
echo "This will install my scripts as well.\n"

printf "continue?(y/n): " ; read -r response
[ "$response" != "y" ] && exit

clear
echo "Copying my config files...\n"
git clone https://github.com/kibybyte/i3-xorg
cd i3-xorg
rm -rf ./LICENSE

for file in ./*
do
    location=$(cat $file | head -2 | tail -1 | awk '{printf $2}')
    location="$(eval "echo $location")"
    if [ ! -d "${location%/*}" ]
    then
        mkdir -p "${location%/*}"
    fi
    cat $file > $location
done

clear
echo "installing packages" && sleep 5
sudo pacman -Syu xorg-server i3-gaps i3blocks maim pulseaudio pulseaudio-alsa pulseaudio-bluetooth bluez bluez-utils fish ttf-jetbrains-mono pango network-manager-applet dmenu ranger mate-calc firefox dunst redshift feh light xorg-xinit alacritty

paru --version || { git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -sric }

clear
echo "It will take quite some time to compile the following AUR packages, so grab a cup of coffee or tea..." && sleep 5

paru -S ttf-ms-fonts adwaita-qt clipman motivate 

chsh -s /usr/bin/fish
echo "Change /bin/sh to dash?(y/n) "
echo "select n if you want to be safe and are new to linux"
read choice
[ "$choice" = "y" ] && sudo ln -sf /usr/bin/dash /bin/sh
sudo usermod -aG video $USER
