#!/bin/bash
set -e
echo "This install script installs i3 WM and related tools. It uses the Xorg protocol."
echo "Dependencies: git, pacman, a vanilla install of Arch Linux with the base-devel package" 

echo "

	" && sleep 5
echo "Packages which will be installed: xorg-xserver, i3-gaps, i3blocks, paru-bin, maim, pipewire,
                                  pipewire-alsa,pipewire-pulse, bluez, bluez-utils,
                                  fish (will be set to be default shell), ttf-jetbrains-mono,
                                  pango, nm-applet,  dmenu, ranger, mate-calc, firefox, 
                                  clipmenu, dunst, redshift, feh, light, motivate, xfce4-terminal,
				  xwallpaper, xclip, ttf-ms-fonts, adwaita-qt
				  "
echo "This will add my scripts as well.
"


#read -r -p "continue?(y/n): " response
#[ "$response" != "y" ] && exit

clear
echo "Copying my config files..."
cd /tmp
git clone https://github.com/kibybyte/i3-xorg
cd i3-xorg 
rm -rf ./LICENSE
read -r -p "Include my scripts found at kibybyte/bin? Not having them may break some minor stuff. (y/n)" binchoice
if [ "$binchoice" = "y" ] ; then
	mkdir -p "$HOME"/.local
	git clone https://github.com/kibybyte/bin
	rm bin/LICENSE
	mv bin "$HOME"/.local/
fi

for file in ./*
do
    location=$(cat $file | head -2 | tail -1 | awk '{printf $2}')
    location="$(eval "echo $location")"
    if [ ! -d "${location%/*}" ]
    then
        mkdir -p "${location%/*}"
    fi
    cp $file $location
done

clear
echo "installing packages" && sleep 5
sudo pacman -Syu xorg-server xwallpaper i3-gaps i3blocks maim pipewire pipewire-alsa pipewire-pulse bluez bluez-utils fish ttf-jetbrains-mono pango network-manager-applet dmenu ranger mate-calc firefox dunst redshift feh light xorg-xinit xfce4-terminal xclip gvfs gvfs-mtp nemo xorg-xinput xorg-xev github-cli

paru --version || { git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -sric; }

clear
echo "It will take quite some time to compile the following AUR packages, so grab a cup of coffee or tea..." && sleep 5

paru -S ttf-ms-fonts adwaita-qt clipman motivate 

clear
chsh -s /usr/bin/fish
[ $(readlink -nf /bin/sh) != /usr/bin/dash ] && sudo ln -sf /usr/bin/dash /bin/sh
sudo usermod -aG video $USER

clear
mkdir -p $HOME/pics
cd $HOME/pics
git clone https://github.com/kibybyte/wallpapers
