#!/bin/sh

#It is assumed you will need at the most 3 partitions: /, /boot and /home. It is also
#assumed that you want partitions to be mounted at /mnt and so forth. Edit it as you
#see fit. Further it is to be noted that this script assumes a BIOS installation. Edit it if you
#you want, however it would make more sense to use the official installer that is packaged with
#Arch Linux for a UEFI install.

echo "Press Ctrl+D to skip mountpoint. Order is root, then boot, then home. Partition names to be selected only. eg: choose sda1 instead of /dev/sda1"
lsblk
echo "select root partition: "
read root && mount /dev/$root /mnt
echo "select boot partition: "
read boot && mount /dev/$boot /mnt/boot
echo "select home partition: "
read home && mount /dev/$home /mnt/home

reflector --download-timeout 1 --protocol https --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
pacstrap /mnt base base-devel linux linux-firmware neovim sudo man-db man-pages texinfo networkmanager 
genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt pacman -Syu grub --noconfirm
lsblk
echo "enter device to install bootloader to: "
read bootloader
arch-chroot /mnt grub-install --force /dev/$bootloader
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt timedatectl set-local-rtc 0
arch-chroot /mnt timedatectl set-timezone Asia/Kolkata
arch-chroot /mnt timedatectl set-ntp true
arch-chroot /mnt hwclock --systohc
echo "en_GB.UTF-8 UTF-8" >> /mnt/etc/locale.gen
echo "en_IN UTF-8" >> /mnt/etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale-gen
arch-chroot /mnt locale-gen
arch-chroot /mnt localectl set-locale LANG=en_GB.UTF-8
arch-chroot /mnt localectl set-locale LC_TIME=en_IN.UTF-8
arch-chroot /mnt localectl set-locale LC_MEASUREMENT=en_IN.UTF-8
arch-chroot /mnt localectl set-locale LC_TELEPHONE=en_IN.UTF-8
arch-chroot /mnt localectl set-locale LC_MONETARY=en_IN.UTF-8
arch-chroot /mnt localectl set-locale LC_NUMERIC=en_IN.UTF-8
arch-chroot /mnt localectl set-x11-keymap us

echo "Set hostname of machine: "
read hostname
arch-chroot /mnt hostnamectl set-hostname $hostname

echo "127.0.0.1       localhost" >> /mnt/etc/hosts
echo "::1             localhost" >> /mnt/etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /mnt/etc/hosts

echo "Set root password"
arch-chroot /mnt passwd

echo "username: "
read username
arch-chroot /mnt useradd -m -G wheel $username
arch-chroot /mnt passwd $username
arch-chroot /mnt env EDITOR=nvim visudo		#Uncomment line about sudo access with visudo as well as entry without password

umount -R /mnt
reboot
