#!/usr/bin/env bash
echo "This install script installs sway WM and related tools. It uses the Wayland protocol."


echo "Dependencies: git, pacman, a vanilla install of Arch Linux with the base-devel package "

echo "Packages that will be installed: sway waybar wl-clipboard dash bat mpv imv zathura \
zathura-pdf-mupdf alacritty grim slurp neovim otf-font-awesome pipewire pipewire-pulse \
pipewire-alsa bluez bluez-utils fish ttf-jetbrains-mono pango network-manager-applet ranger \
mate-calc dunst light lxsession gammastep"

echo "Change /bin/sh to dash?(y/n) "
echo "select n if you want to be safe and are new to linux"
read choice
 
read -p "Include my scripts found at kibybyte/bin? Not having them may break some minor stuff. (y/n)" binchoice

read -p "Do you want wallpapers? (y/n)" wallchoice

echo "Continue? (y/n)"
read response
[ $response = "y" ] || exit

git clone https://github.com/kibybyte/sway || exit
cd sway || exit 
rm -f ./LICENSE
if [ "$binchoice" = "y" ] ; then
	mkdir -p $HOME/.local
	git clone https://github.com/kibybyte/bin
	rm bin/LICENSE
	mv bin $HOME/.local/
fi

for file in ./*
do
    location="$(awk 'NR==2 { print $2 }' "$file")"
    location="$(eval "echo $location")"
    [ ! -d "${location%/*}" ] && mkdir -p "${location%/*}"
    cat "$file" > "$location"
done


sudo pacman -S --noconfirm sway waybar wl-clipboard dash bat mpv imv zathura zathura-pdf-mupdf alacritty grim slurp neovim otf-font-awesome pipewire pipewire-pulse pipewire-alsa bluez bluez-utils fish ttf-jetbrains-mono pango network-manager-applet ranger mate-calc dunst light lxsession gammastep firefox

paru --version || git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -sric --noconfirm

paru -S --noconfirm ttf-ms-fonts adwaita-qt clipman motivate 

chsh -s /usr/bin/fish
if [ "$choice" = "y" ] && sudo ln -sf /usr/bin/dash /bin/sh
sudo usermod -aG video $USER

clear
if [ "$wallchoice" = "y" ] ; then
		mkdir -p $HOME/pics
		cd $HOME/pics
		git clone https://github.com/kibybyte/wallpapers
fi
echo "done"
