#!/bin/env bash
set -e

echo "This is the UEFI minimal install. It installs a configuration tailored to my needs.
You might be looking for universal-uefi from this same repo for something a little more universal."

if lscpu | grep GenuineIntel 1>/dev/null 2>&1 ; then
	cpu="intel"
elif lscpu | grep AuthenticAMD 1>/dev/null 2>&1 ; then
	cpu="amd"
fi


lsblk
read -p "select disk(eg: sda, not sda1): " disk
cgdisk /dev/"$disk"

clear
echo "Press Ctrl+D to skip mountpoint. Order is root, then boot, then home."
echo "Partition names to be selected only. eg: choose sda1 instead of /dev/sda1"
lsblk && echo "Press Ctrl+D to skip mountpoint."
read -p "select root partition: " root
mkfs.ext4 /dev/$root && mount /dev/$root /mnt 
lsblk && echo "Press Ctrl+D to skip mountpoint."
read -p "select boot partition: " boot
mkfs.fat -F32 /dev/$boot && mkdir /mnt/boot && mount /dev/$boot /mnt/boot 
lsblk && echo "Press Ctrl+D to skip mountpoint."
read -p "select home partition: " home
mkfs.ext4 /dev/$home && mkdir /mnt/home && mount /dev/$home /mnt/home
clear

reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
pacstrap /mnt base base-devel git linux linux-firmware neovim nano sudo man-db man-pages texinfo $cpu-ucode dash
genfstab -U /mnt >> /mnt/etc/fstab

mkdir -p /mnt/boot/loader/entries

arch-chroot /mnt bootctl install
echo "default arch.conf
timeout 0
editor no" > /mnt/boot/loader/loader.conf

uuid="$(blkid /dev/$root -s UUID -o value)"
echo "title   Arch Linux (linux)
linux   /vmlinuz-linux
initrd  /$cpu-ucode.img
initrd  /initramfs-linux.img
options	 root=UUID=$uuid rw" > /mnt/boot/loader/entries/arch.conf


arch-chroot /mnt systemctl enable systemd-networkd
mkdir -p /mnt/etc/systemd/system/systemd-networkd-wait-online.service.d/
echo "[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any" > /mnt/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf

echo "[Match]
Name=en*

[Network]
DHCP=yes" > /mnt/etc/systemd/network/20-wired.network


timedatectl set-local-rtc 0
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
timedatectl set-ntp true
arch-chroot /mnt hwclock --systohc
echo "en_GB.UTF-8 UTF-8" >> /mnt/etc/locale.gen
echo "en_IN UTF-8" >> /mnt/etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen

echo "LANG=en_GB.UTF-8    
LC_TIME=en_IN.UTF-8     
LC_MEASUREMENT=en_IN.UTF-8    
LC_TELEPHONE=en_IN.UTF-8    
LC_MONETARY=en_IN.UTF-8    
LC_NUMERIC=en_IN.UTF-8" >> /mnt/etc/locale.conf

clear

read -p "Set hostname of machine: " hostname
echo "$hostname" > /mnt/etc/hostname

echo "127.0.0.1       localhost
::1             localhost
127.0.1.1       $hostname.localdomain $hostname" >> /mnt/etc/hosts

echo "Set root password"
arch-chroot /mnt passwd

read -p "username: " username
arch-chroot /mnt useradd -m -G wheel $username
sed -i '85i \%wheel ALL=(ALL) NOPASSWD: ALL' /mnt/etc/sudoers || echo "WARNING: run visudo on reboot and correct as required."
arch-chroot /mnt passwd $username

echo "EDITOR=nvim
GTK_THEME=Adwaita:dark
QT_STYLE_OVERRIDE=Adwaita-dark" > /mnt/etc/environment

umount -R /mnt
reboot
