#!/bin/env bash

echo "This is the universal UEFI minimal install."

if lscpu | grep GenuineIntel 1>/dev/null 2>&1 ; then
	cpu="intel"
elif lscpu | grep AuthenticAMD 1>/dev/null 2>&1 ; then
	cpu="amd"
fi


lsblk
echo "select disk(eg: sda, not sda1): "
read disk
cgdisk /dev/$disk

echo "Press Ctrl+D to skip mountpoint. Order is root, then boot, then home."
echo "Partition names to be selected only. eg: choose sda1 instead of /dev/sda1"
lsblk
echo "select root partition: "
read root && mkfs.ext4 /dev/$root && mount /dev/$root /mnt
clear
lsblk
echo "select boot partition: "
read boot && mkfs.fat -F32 /dev/$boot && mkdir /mnt/boot && mount /dev/$boot /mnt/boot
clear
lsblk
echo "select home partition: "
read home && mkfs.ext4 /dev/$home && mkdir /mnt/home && mount /dev/$home /mnt/home

reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
pacstrap /mnt base base-devel git linux linux-firmware neovim nano sudo man-db man-pages texinfo networkmanager $cpu-ucode
genfstab -U /mnt >> /mnt/etc/fstab

mkdir -p /mnt/boot/loader/entries

arch-chroot /mnt bootctl install
echo "default arch.conf
timeout 0
editor no" > /mnt/boot/loader/loader.conf

uuid="$(blkid /dev/$root -s UUID -o value)"
echo "title   Arch Linux (linux)
linux   /vmlinuz-linux
initrd  /$cpu-ucode.img
initrd  /initramfs-linux.img
options	 root=UUID=$uuid rw" > /mnt/boot/loader/entries/arch.conf

arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt timedatectl set-local-rtc 0
timezone=$(tzselect | tail -n 1)
ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime
arch-chroot /mnt timedatectl set-ntp true
arch-chroot /mnt hwclock --systohc
echo "en_GB.UTF-8 UTF-8" >> /mnt/etc/locale.gen
echo "en_IN UTF-8" >> /mnt/etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen


echo "LANG=en_GB.UTF-8" >> /mnt/etc/locale.conf
echo "LC_TIME=en_IN.UTF-8" >> /mnt/etc/locale.conf
echo "LC_MEASUREMENT=en_IN.UTF-8" >> /mnt/etc/locale.conf
echo "LC_TELEPHONE=en_IN.UTF-8" >> /mnt/etc/locale.conf
echo "LC_MONETARY=en_IN.UTF-8" >> /mnt/etc/locale.conf
echo "LC_NUMERIC=en_IN.UTF-8" >> /mnt/etc/locale.conf

echo "Set hostname of machine: "
read hostname
echo "$hostname" > /mnt/etc/hostname

echo "127.0.0.1       localhost" >> /mnt/etc/hosts
echo "::1             localhost" >> /mnt/etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /mnt/etc/hosts

echo "Set root password"
arch-chroot /mnt passwd

echo "username: "
read username
arch-chroot /mnt useradd -m -G wheel $username
arch-chroot /mnt passwd $username

umount -R /mnt
reboot
